### ISSUE TITLE
Button should be hidden if no URL is provided

### ISSUE THREAD

**Issue by dhhuynh2** [v-ngu/backstage-plugin-bulletin-board#15]
Hi - thanks for the plugin, I've been playing around with it and it looks promising. Just randomly noticed - should the `Open URL` button even be displayed if no URL is provided, since it's an optional field? Seems pretty straightforward, I could help contribute with a PR if we think that makes sense.

**Comment by v-ngu** [comment]
It makes sense. Go ahead :)

**Comment by v-ngu** [comment]
Have you been able to take a look at it?
