### ISSUE TITLE
Custom title and subtitle

### ISSUE THREAD

**Issue by felipe-nardon** [v-ngu/backstage-plugin-bulletin-board#22]
Hello!!
Thanks for the plugin! I'm using in my company. It's is very useful!
Could you add custom title and subtitle?

Like this:
```
type Props = {
  title?: string;
  subtitle?: string;
};
export const BulletinBoardPage = (props: Props) => {

...

<Header title={props.title ?? 'Bulletin Board'} subtitle={props.subtitle ?? 'A basic place to share ideas and links with your team.'} />
```

Thank You!!!

**Comment by v-ngu** [comment]
Thanks! It's good to hear that you like the plugin. 

It isn't a feature other plugins seem to follow. If you have examples please share them.

**Comment by felipe-nardon** [comment]
Sure!

[Explore plugin](https://github.com/backstage/backstage/blob/6325e9cd11ce171e255aa0b377135b5b0fffabe7/plugins/explore/src/components/ExploreLayout/ExploreLayout.tsx#L81)

[SplunkOnCall plugin](https://github.com/backstage/backstage/blob/6325e9cd11ce171e255aa0b377135b5b0fffabe7/plugins/splunk-on-call/src/components/SplunkOnCallPage.tsx#L47)

[Bazaar plugin](https://github.com/backstage/backstage/blob/6325e9cd11ce171e255aa0b377135b5b0fffabe7/plugins/bazaar/src/components/HomePage/HomePage.tsx#L49)

[Playlist plugin](https://github.com/backstage/backstage/blob/6325e9cd11ce171e255aa0b377135b5b0fffabe7/plugins/playlist/src/components/PlaylistPage/PlaylistHeader.tsx#L121)

[Apollo Explorer plugin](https://github.com/backstage/backstage/blob/6325e9cd11ce171e255aa0b377135b5b0fffabe7/plugins/apollo-explorer/src/components/ApolloExplorerPage/ApolloExplorerPage.tsx#L48)

[Settings plugin](https://github.com/backstage/backstage/blob/6325e9cd11ce171e255aa0b377135b5b0fffabe7/plugins/user-settings/src/components/SettingsLayout/SettingsLayout.tsx#L74)

[GraphQL Voyager plugin](https://github.com/backstage/backstage/blob/6325e9cd11ce171e255aa0b377135b5b0fffabe7/plugins/graphql-voyager/src/components/GraphQLVoyagerPage/GraphQLVoyagerPage.tsx#L56)

[Tech Radar plugin](https://github.com/backstage/backstage/blob/6325e9cd11ce171e255aa0b377135b5b0fffabe7/plugins/tech-radar/src/components/RadarPage.tsx#L73)

**Comment by felipe-nardon** [comment]
Of course!

I'll open a pull request!

Thanks

**Comment by v-ngu** [comment]
Thanks for everything
