### ISSUE TITLE
Getting Error with code 500 while submitting a new idea 

### ISSUE THREAD

**Issue by vaibhav-shimpi-maersk** [v-ngu/backstage-plugin-bulletin-board#28]
I have recently installed the bulletin board and trying to test by adding the new ideas via bulletin board screen. After clicking save button, it is giving 500 on network tab. The network trace is mention below - 

API URL - http://localhost:7007/api/bulletin-board/bulletins

PAyload - {"id":"DQeoA75Nf6y_NtGUxl-ba","title":"React","url":"https://legacy.reactjs.org/docs/context.html","description":"React description","tags":[],"user":null}

Response - 
{
    "error": {
        "name": "error",
        "message": "insert into \"bulletins\" (\"bulletin_description\", \"bulletin_id\", \"bulletin_tags\", \"bulletin_title\", \"bulletin_url\", \"created_at\", \"created_by\", \"updated_at\", \"updated_by\") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) - null value in column \"created_by\" of relation \"bulletins\" violates not-null constraint",
        "length": 392,
        "severity": "ERROR",
        "code": "23502",
        "detail": "Failing row contains (DQeoA75Nf6y_NtGUxl-ba, React, React description, https://github.com/Maersk-Global/gco-test-dotnet/blob/main/catal..., , null, null, 2023-06-20 08:41:56.468+00, 2023-06-20 08:41:56.468+00).",
        "schema": "public",
        "table": "bulletins",
        "column": "created_by",
        "file": "execMain.c",
        "line": "1968",
        "routine": "ExecConstraints",
        "stack": "error: insert into \"bulletins\" (\"bulletin_description\", \"bulletin_id\", \"bulletin_tags\", \"bulletin_title\", \"bulletin_url\", \"created_at\", \"created_by\", \"updated_at\", \"updated_by\") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) - null value in column \"created_by\" of relation \"bulletins\" violates not-null constraint\n    at Parser.parseErrorMessage (/Users/vaibhav.shimpi/source/repos/*******/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/Users/vaibhav.shimpi/source/repos/*******/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/Users/vaibhav.shimpi/source/repos/*******/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/Users/vaibhav.shimpi/source/repos/*******/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
    },
    "request": {
        "method": "POST",
        "url": "/bulletins"
    },
    "response": {
        "statusCode": 500
    }
}

**Comment by v-ngu** [comment]
Have you installed the backend as well?

**Comment by vaibhav-shimpi-maersk** [comment]
Yes, following is the package.json - 

app - >
{
  "name": "app",
  "version": "0.0.0",
  "private": true,
  "bundled": true,
  "backstage": {
    "role": "frontend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "clean": "backstage-cli package clean",
    "test": "backstage-cli package test",
    "lint": "backstage-cli package lint",
    "test:e2e": "cross-env PORT=3001 start-server-and-test start http://localhost:3001 cy:dev",
    "test:e2e:ci": "cross-env PORT=3001 start-server-and-test start http://localhost:3001 cy:run",
    "cy:dev": "cypress open",
    "cy:run": "cypress run --browser chrome"
  },
  "dependencies": {
    "@backstage/app-defaults": "^1.3.1",
    "@backstage/catalog-model": "^1.3.0",
    "@backstage/cli": "^0.22.7",
    "@backstage/core-app-api": "^1.8.0",
    "@backstage/core-components": "^0.13.1",
    "@backstage/core-plugin-api": "^1.5.1",
    "@backstage/integration-react": "^1.1.13",
    "@backstage/plugin-api-docs": "^0.9.4",
    "@backstage/plugin-bazaar": "^0.2.9",
    "@backstage/plugin-catalog": "^1.11.1",
    "@backstage/plugin-catalog-common": "^1.0.13",
    "@backstage/plugin-catalog-graph": "^0.2.30",
    "@backstage/plugin-catalog-import": "^0.9.8",
    "@backstage/plugin-catalog-react": "^1.6.0",
    "@backstage/plugin-github-actions": "^0.5.18",
    "@backstage/plugin-home": "^0.5.2",
    "@backstage/plugin-kubernetes": "^0.9.1",
    "@backstage/plugin-lighthouse": "^0.4.3",
    "@backstage/plugin-org": "^0.6.8",
    "@backstage/plugin-permission-react": "^0.4.12",
    "@backstage/plugin-scaffolder": "^1.13.1",
    "@backstage/plugin-search": "^1.3.1",
    "@backstage/plugin-search-react": "^1.6.1",
    "@backstage/plugin-sonarqube": "^0.6.7",
    "@backstage/plugin-stack-overflow": "^0.1.16",
    "@backstage/plugin-tech-radar": "^0.6.4",
    "@backstage/plugin-techdocs": "^1.6.3",
    "@backstage/plugin-techdocs-module-addons-contrib": "^1.0.13",
    "@backstage/plugin-techdocs-react": "^1.1.6",
    "@backstage/plugin-todo": "^0.2.20",
    "@backstage/plugin-user-settings": "^0.7.3",
    "@backstage/theme": "^0.3.0",
    "@deepan10/backstage-plugin-blackduck": "^1.0.1",
    "@k-phoen/backstage-plugin-announcements": "^0.0.14",
    "@k-phoen/backstage-plugin-grafana": "^0.1.22",
    "@material-ui/core": "^4.12.2",
    "@material-ui/icons": "^4.9.1",
    "@roadiehq/backstage-plugin-github-insights": "^2.3.9",
    "@roadiehq/backstage-plugin-jira": "^2.4.5",
    "@vippsno/plugin-azure-resources": "^1.0.8",
    "backstage-plugin-bulletin-board": "^0.4.1",
    "backstage-plugin-techdocs-addon-mermaid": "^0.6.3",
    "history": "^5.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.3.0",
    "react-use": "^17.2.4"
  },
  "devDependencies": {
    "@backstage/plugin-kubernetes": "^0.9.1",
    "@backstage/plugin-sonarqube": "^0.6.7",
    "@backstage/plugin-vault": "^0.1.12",
    "@backstage/test-utils": "^1.3.1",
    "@k-phoen/backstage-plugin-grafana": "^0.1.22",
    "@roadiehq/backstage-plugin-github-insights": "^2.3.9",
    "@roadiehq/backstage-plugin-github-pull-requests": "^2.5.6",
    "@roadiehq/backstage-plugin-prometheus": "^2.4.5",
    "@testing-library/jest-dom": "^5.10.1",
    "@testing-library/react": "^12.1.3",
    "@testing-library/user-event": "^14.0.0",
    "@types/node": "^16.11.26",
    "@types/react-dom": "*",
    "cross-env": "^7.0.0",
    "cypress": "^9.7.0",
    "eslint-plugin-cypress": "^2.10.3",
    "start-server-and-test": "^1.10.11"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "files": [
    "dist"
  ]
}

--------------
backend - 

{
  "name": "backend",
  "version": "0.0.0",
  "main": "dist/index.cjs.js",
  "types": "src/index.ts",
  "private": true,
  "backstage": {
    "role": "backend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "lint": "backstage-cli package lint",
    "test": "backstage-cli package test",
    "clean": "backstage-cli package clean",
    "build-image": "docker build ../.. -f Dockerfile --tag backstage"
  },
  "dependencies": {
    "@backstage/backend-common": "^0.18.5",
    "@backstage/backend-tasks": "^0.5.2",
    "@backstage/catalog-client": "^1.4.1",
    "@backstage/catalog-model": "^1.3.0",
    "@backstage/config": "^1.0.7",
    "@backstage/plugin-app-backend": "^0.3.45",
    "@backstage/plugin-auth-backend": "^0.18.3",
    "@backstage/plugin-auth-node": "^0.2.14",
    "@backstage/plugin-bazaar-backend": "^0.2.8",
    "@backstage/plugin-catalog-backend": "^1.9.1",
    "@backstage/plugin-catalog-backend-module-github": "^0.3.0",
    "@backstage/plugin-catalog-backend-module-msgraph": "^0.5.4",
    "@backstage/plugin-kubernetes-backend": "^0.11.0",
    "@backstage/plugin-lighthouse-backend": "^0.2.1",
    "@backstage/plugin-permission-common": "^0.7.5",
    "@backstage/plugin-permission-node": "^0.7.8",
    "@backstage/plugin-proxy-backend": "^0.2.39",
    "@backstage/plugin-scaffolder-backend": "^1.14.0",
    "@backstage/plugin-search-backend": "^1.3.1",
    "@backstage/plugin-search-backend-module-pg": "^0.5.6",
    "@backstage/plugin-search-backend-node": "^1.2.1",
    "@backstage/plugin-sonarqube-backend": "^0.1.10",
    "@backstage/plugin-stack-overflow-backend": "^0.2.1",
    "@backstage/plugin-techdocs-backend": "^1.6.2",
    "@backstage/plugin-todo-backend": "^0.1.42",
    "@backstage/plugin-vault-backend": "^0.3.1",
    "@k-phoen/backstage-plugin-announcements-backend": "^0.1.4",
    "@octokit/core": "^4.2.1",
    "@vippsno/plugin-azure-resources-backend": "^1.0.5",
    "app": "link:../app",
    "backstage-plugin-bulletin-board-backend": "^0.2.1",
    "better-sqlite3": "^8.0.0",
    "dockerode": "^3.3.1",
    "express": "^4.17.1",
    "express-promise-router": "^4.1.0",
    "libsodium-wrappers": "^0.7.11",
    "pg": "^8.3.0",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "@backstage/cli": "^0.22.7",
    "@backstage/plugin-kubernetes-backend": "^0.11.0",
    "@types/dockerode": "^3.3.0",
    "@types/express": "^4.17.6",
    "@types/express-serve-static-core": "^4.17.5",
    "@types/luxon": "^2.0.4"
  },
  "files": [
    "dist"
  ]
}

**Comment by v-ngu** [comment]
I  am not sure how to replicate the error. I would suggest uninstalling everything first then install again. Here are the links:

FE: https://github.com/v-ngu/backstage-plugin-bulletin-board/blob/main/plugins/bulletin-board/README.md
BE: https://github.com/v-ngu/backstage-plugin-bulletin-board/blob/main/plugins/bulletin-board-backend/README.md

**Comment by vaibhav-shimpi-maersk** [comment]
I have reinstalled the packages but still getting 500. Here is the error - 

backstage error Request failed with status 500 insert into "bulletins" ("bulletin_description", "bulletin_id", "bulletin_tags", "bulletin_title", "bulletin_url", "created_at", "created_by", "updated_at", "updated_by") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) - **_null value in column "created_by" of relation "bulletins" violates not-null constraint type_**=errorHandler length=328 name=error severity=ERROR code=23502 detail=Failing row contains (G_NkdA6jcr0bgRwUU5rPF, Test, TEst, http://google.com, , null, null, 2023-06-21 07:57:17.972+00, 2023-06-21 07:57:17.972+00). hint=undefined position=undefined internalPosition=undefined internalQuery=undefined where=undefined schema=public table=bulletins column=created_by dataType=undefined constraint=undefined file=execMain.c line=1968 routine=ExecConstraints stack=error: insert into "bulletins" ("bulletin_description", "bulletin_id", "bulletin_tags", "bulletin_title", "bulletin_url", "created_at", "created_by", "updated_at", "updated_by") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) - null value in column "created_by" of relation "bulletins" violates not-null constraint

**Comment by vaibhav-shimpi-maersk** [comment]
It seem the created-by is not getting passed to the post action.
